# Generated by Django 4.1.6 on 2023-02-08 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecole", "0002_remove_programme_prix_programme_montant_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="classe", name="nom",),
    ]
