# Generated by Django 4.1.6 on 2023-02-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0002_eleve_alter_utilisateur_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="adresse",
            field=models.CharField(
                default=None,
                help_text="Adresse de l'élève",
                max_length=50,
                null=True,
                verbose_name="Adresse de l'élève",
            ),
        ),
        migrations.AlterField(
            model_name="eleve",
            name="autre_prenom",
            field=models.CharField(
                default=None,
                help_text="Autre prénom de l'élève",
                max_length=50,
                null=True,
                verbose_name="Autre prénom de l'élève",
            ),
        ),
        migrations.AlterField(
            model_name="eleve",
            name="code_postal",
            field=models.CharField(
                default=None,
                help_text="Code postal",
                max_length=50,
                null=True,
                verbose_name="Code postal",
            ),
        ),
        migrations.AlterField(
            model_name="eleve",
            name="telephone",
            field=models.CharField(
                default=None,
                help_text="Téléphone de l'élève",
                max_length=50,
                null=True,
                verbose_name="Téléphone de l'élève",
            ),
        ),
    ]
