# Generated by Django 4.1.6 on 2023-02-08 02:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0003_alter_eleve_adresse_alter_eleve_autre_prenom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="matricule_id",
            field=models.CharField(
                default=125,
                error_messages={},
                help_text="Le matricule doit etre compose de 10 chiffres",
                max_length=10,
                primary_key=True,
                serialize=False,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_matricule",
                        message="Le matricule doit etre compose de 10 chiffres",
                        regex="^[0-9]{10}$",
                    )
                ],
                verbose_name="Le numero de Matricule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="eleve",
            name="utilisateur",
            field=models.OneToOneField(
                help_text="Compte de l'élève",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Compte de l'élève",
            ),
        ),
    ]
