# Generated by Django 4.1.6 on 2023-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comptes", "0004_eleve_matricule_id_alter_eleve_utilisateur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eleve",
            name="autre_prenom",
            field=models.CharField(
                default=None,
                help_text="Autre prénom de l'élève",
                max_length=50,
                verbose_name="Autre prénom de l'élève",
            ),
        ),
    ]
